# Generated by Django 5.1 on 2024-08-23 07:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PickUpWarehouseLocation',
            fields=[
                ('created_by', models.UUIDField(blank=True, help_text='User Id who created this record.', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='User Id who updated this record.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time at which this record is created', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time at which this record is last updated.', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plot_no', models.CharField(blank=True, max_length=100, null=True)),
                ('location_name', models.CharField(blank=True, max_length=255, null=True)),
                ('street', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=6)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wearhouselocatoin', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'App Model - pickupwearhouselocation',
                'verbose_name_plural': 'App Model - pickupwearhouselocation',
            },
        ),
    ]
