# Generated by Django 5.1 on 2024-08-23 11:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0002_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('created_by', models.UUIDField(blank=True, help_text='User Id who created this record.', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='User Id who updated this record.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time at which this record is created', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time at which this record is last updated.', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=225, null=True)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('product_quality', models.CharField(choices=[('GOOD', 'good'), ('BAD', 'bad')], max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_type', to='models_app.category')),
            ],
            options={
                'verbose_name': 'Model App - ProductType',
                'verbose_name_plural': 'Model App - ProductType',
            },
        ),
    ]
