# Generated by Django 5.1 on 2024-08-24 11:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0003_producttype'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('created_by', models.UUIDField(blank=True, help_text='User Id who created this record.', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='User Id who updated this record.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time at which this record is created', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time at which this record is last updated.', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_tittle', models.CharField(blank=True, max_length=255, null=True)),
                ('about_the_brand', models.CharField(blank=True, max_length=2000, null=True)),
                ('product_brand', models.CharField(blank=True, max_length=2000, null=True)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_category', to='models_app.category')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_product_type', to='models_app.producttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Model App - ProductType',
                'verbose_name_plural': 'Model App - ProductType',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PriceStructure',
            fields=[
                ('created_by', models.UUIDField(blank=True, help_text='User Id who created this record.', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='User Id who updated this record.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time at which this record is created', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time at which this record is last updated.', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hsn_code', models.CharField(blank=True, max_length=10, null=True)),
                ('sale_price', models.CharField(blank=True, max_length=10, null=True)),
                ('mrp', models.CharField(blank=True, max_length=10, null=True)),
                ('tax_code', models.CharField(blank=True, max_length=10, null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product_price_structure', to='models_app.product')),
            ],
            options={
                'verbose_name': 'Model App - Price Structure',
                'verbose_name_plural': 'Model App - Price Structure',
            },
        ),
        migrations.CreateModel(
            name='ShippingDetails',
            fields=[
                ('created_by', models.UUIDField(blank=True, help_text='User Id who created this record.', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='User Id who updated this record.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time at which this record is created', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time at which this record is last updated.', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_weight', models.CharField(blank=True, max_length=125, null=True)),
                ('return_policy', models.CharField(blank=True, default=True, max_length=555, null=True)),
                ('packed_box_dimensions_length', models.CharField(blank=True, max_length=100, null=True)),
                ('packed_box_dimensions_height', models.CharField(blank=True, max_length=100, null=True)),
                ('pick_up_location', models.ManyToManyField(blank=True, max_length=255, to='models_app.pickupwarehouselocation')),
            ],
            options={
                'verbose_name': 'Model App - Shipping Detail',
                'verbose_name_plural': 'Model App - Shipping Detail',
            },
        ),
    ]
