# Generated by Django 5.1 on 2024-08-24 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0004_product_pricestructure_shippingdetails'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-created_at',), 'verbose_name': 'Model App - Product', 'verbose_name_plural': 'Model App - Product'},
        ),
        migrations.AlterField(
            model_name='shippingdetails',
            name='pick_up_location',
            field=models.ManyToManyField(blank=True, max_length=255, related_name='shipping_detail', to='models_app.pickupwarehouselocation'),
        ),
    ]
