# Generated by Django 5.1 on 2024-08-28 04:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0005_alter_product_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DropLocation',
            fields=[
                ('created_by', models.UUIDField(blank=True, help_text='User Id who created this record.', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='User Id who updated this record.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time at which this record is created', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time at which this record is last updated.', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('location_name', models.CharField(blank=True, max_length=100, null=True)),
                ('area', models.CharField(blank=True, max_length=255, null=True)),
                ('street', models.CharField(blank=True, max_length=255, null=True)),
                ('pickup_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drop_location', to='models_app.pickupwarehouselocation')),
            ],
            options={
                'verbose_name': 'Model App - Drop Location',
                'verbose_name_plural': 'Model App - Drop Location',
            },
        ),
    ]
