# Generated by Django 5.1 on 2024-08-29 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0008_alter_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='prfoile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile'),
        ),
    ]
