# Generated by Django 5.1 on 2024-08-30 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0009_profile_prfoile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='list_of_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
