# Generated by Django 5.1 on 2024-08-31 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0010_genre_list_of_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='is_genre_book',
            field=models.BooleanField(default=False),
        ),
    ]
