# Generated by Django 5.1 on 2024-08-20 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='auth_key',
            field=models.CharField(default='8ed295c64707160dd1421bf4ebc72fb5', max_length=32, unique=True),
        ),
    ]
