# Generated by Django 5.1 on 2024-08-21 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app_user', '0006_alter_user_auth_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='auth_key',
            field=models.CharField(default='8107091448a6a23773eb50a343270a33', max_length=32, unique=True),
        ),
    ]
