# Generated by Django 5.1 on 2024-08-22 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app_user', '0007_alter_user_auth_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='auth_key',
            field=models.CharField(default='9a72bf75946f79af5a8bc9be9199f61c', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
