# Generated by Django 5.1 on 2024-08-22 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app_user', '0008_user_otp_alter_user_auth_key_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='auth_key',
            field=models.CharField(default='9db5ba6903d271c1c39ed9e09013f887', max_length=32, unique=True),
        ),
    ]
