# Generated by Django 5.1 on 2024-08-23 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app_user', '0009_user_is_verified_alter_user_auth_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='auth_key',
            field=models.CharField(default='a971e33fb9ffe28169549d52a3e5363b', max_length=32, unique=True),
        ),
    ]
