# Generated by Django 5.1 on 2024-08-29 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app_user', '0010_alter_user_auth_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='auth_key',
            field=models.CharField(default='4ee23a7ccfe60150264b1dee881d985e', max_length=32, unique=True),
        ),
    ]
