# Generated by Django 5.1 on 2024-08-31 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app_user', '0011_alter_user_auth_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='auth_key',
            field=models.CharField(default='ef1aa1235c796d301d4c41372b757589', max_length=32, unique=True),
        ),
    ]
